import type { ReactNode } from "react";
import { businessConfig } from "../config/business";

const emailHref = businessConfig.contactEmail.startsWith("PLACEHOLDER_") ? undefined : `mailto:${businessConfig.contactEmail}`;
const ContactEmail = () => emailHref ? <a href={emailHref}>{businessConfig.contactEmail}</a> : <strong>{businessConfig.contactEmail}</strong>;
const LegalNotice = () => <p className="page-notice">AI Business Agent is an independent software product and is not affiliated with, sponsored by, or endorsed by Meta Platforms, Inc. Instagram is a trademark of Meta Platforms, Inc.</p>;
function Intro({ label, title, children }: { label: string; title: string; children: ReactNode }) { return <header className="legal-header"><span className="eyebrow">{label}</span><h1>{title}</h1><div className="legal-summary">{children}</div></header>; }

export function PrivacyPage() { return <section className="legal-page"><article className="container narrow legal-content"><Intro label="Legal" title="Privacy Policy"><p>This policy explains how {businessConfig.productName} processes information when businesses use the service. The product is under development, and its data practices may evolve as features are introduced.</p><p className="updated">Last updated: September 1, 2026</p></Intro>
<h2>Information we may receive</h2><h3>Business account data</h3><ul><li>Instagram account ID and account username or name</li><li>OAuth permissions and scopes authorized by the business</li><li>Business profile information available through the authorized integration</li></ul><h3>Messaging data</h3><ul><li>Customer message text and conversation identifiers</li><li>Timestamps and message metadata</li><li>Attachment metadata where available</li></ul><h3>Technical data</h3><ul><li>Service logs, request IDs, and error information</li><li>Security and diagnostic information needed to operate and protect the service</li></ul>
<h2>How information is used</h2><p>We process data only as necessary to provide the service, including to:</p><ul><li>Provide Instagram Business messaging functionality</li><li>Generate AI-assisted replies</li><li>Route conversations and support human review</li><li>Use authorized business data and tools to improve response relevance</li><li>Maintain service reliability, diagnose errors, prevent misuse, and protect security</li></ul>
<div className="policy-callout"><strong>Our commitments</strong><ul><li>We do not sell personal data.</li><li>We do not use Meta Platform Data for advertising.</li><li>We do not request or store Instagram passwords.</li><li>Access to Instagram is granted through official Meta/Instagram OAuth.</li></ul></div>
<h2>AI processing</h2><p>Message content may be processed by AI systems to generate replies. Depending on the configured deployment, AI processing may be performed using locally hosted models or selected service providers. Data provided to a service provider is limited to what is necessary for the configured functionality and subject to applicable safeguards.</p>
<h2>Storage and security</h2><p>Application data, including access tokens, is stored by the application backend using reasonable technical and organizational safeguards. Access is restricted to authorized systems and personnel. No storage or transmission method is completely secure.</p>
<h2>Sharing</h2><p>We may share data with infrastructure, hosting, AI, or operational service providers only when needed to provide and secure the service. We may also disclose information when required by law, to protect rights and safety, or during a business transaction subject to appropriate safeguards. We do not sell personal data or Meta Platform Data.</p>
<h2>Retention and deletion</h2><p>Data is retained only as long as necessary to provide the service, comply with legal obligations, resolve disputes, and maintain security. A user or business can request deletion. Verified requests will be completed by deleting or anonymizing relevant data unless retention is legally or operationally required.</p>
<h2>Your choices and rights</h2><p>Businesses can disconnect the integration through their Meta account settings and request access, correction, or deletion of applicable data. Rights may vary by location. See the Data Deletion Instructions page for the request process.</p>
<h2>Contact</h2><p>Questions or privacy requests may be sent to <ContactEmail />. Operator: {businessConfig.legalName}, {businessConfig.country}.</p><LegalNotice /></article></section>; }

export function TermsPage() { return <section className="legal-page"><article className="container narrow legal-content"><Intro label="Legal" title="Terms of Service"><p>These Terms govern access to and use of {businessConfig.productName}, an AI-assisted customer messaging product for businesses.</p><p className="updated">Last updated: September 1, 2026</p></Intro>
<h2>Service description</h2><p>The service helps businesses manage customer conversations through authorized messaging connections. Features may include reply generation, configured low-risk automation, business-specific data or tools, conversation routing, and manager review. The service is an MVP under active development; functionality may change.</p>
<h2>Eligibility and authority</h2><p>You must be legally able to enter these Terms and authorized to act for the business whose account you connect. You are responsible for ensuring your use complies with applicable laws, platform rules, and obligations to customers.</p>
<h2>Account connection</h2><p>Instagram connections use official OAuth. You must authorize only accounts you control or may manage, protect your own credentials, and disconnect access you no longer authorize. We do not request Instagram passwords.</p>
<h2>Third-party platforms</h2><p>Instagram, Meta, and other third-party services are governed by their own terms, policies, availability, and technical requirements. We are not responsible for third-party changes or interruptions. AI Business Agent is not affiliated with or endorsed by Meta unless explicitly stated otherwise.</p>
<h2>Acceptable use</h2><p>You may not use the service to violate law or platform policy; send unlawful, deceptive, abusive, or unsolicited content; infringe rights; attempt unauthorized access; interfere with the service; or process data without a valid legal basis.</p>
<div className="policy-callout"><strong>AI-generated content</strong><p>AI-generated responses may contain errors. Businesses are responsible for configuring automation policies and reviewing responses where appropriate. Use human review for sensitive, high-risk, or consequential conversations.</p></div>
<h2>Service availability</h2><p>The service is provided on an “as available” basis. We may modify, suspend, or discontinue features, and do not guarantee uninterrupted or error-free operation.</p><h2>Intellectual property</h2><p>We retain rights in the service and software. You retain rights in content and business data you provide, subject to permissions necessary to operate the service.</p>
<h2>Limitation of liability</h2><p>To the maximum extent permitted by law, the operator will not be liable for indirect, incidental, special, consequential, or punitive damages, or loss of profits, data, goodwill, or business opportunities. Liability is limited to the amount paid for the service in the three months before the claim or, if no fee was paid, the minimum amount permitted by law.</p>
<h2>Termination</h2><p>You may stop using the service and disconnect accounts at any time. We may suspend access for breach, security risk, legal requirement, or service discontinuation.</p><h2>Changes</h2><p>We may update these Terms as the service develops. The revised date will appear here.</p><h2>Contact</h2><p>Questions may be sent to <ContactEmail />. Operator: {businessConfig.legalName}, {businessConfig.country}.</p><LegalNotice /></article></section>; }

export function DataDeletionPage() { return <section className="legal-page"><article className="container narrow legal-content"><Intro label="Privacy controls" title="Data Deletion Instructions"><p>You can request deletion of data associated with an Instagram Business account connected to {businessConfig.productName}.</p></Intro><h2>How to request deletion</h2><ol className="steps"><li><strong>Disconnect access, if desired.</strong><span>Remove AI Business Agent from your Instagram or Meta account permissions. This stops future access but may not delete existing service data.</span></li><li><strong>Contact us.</strong><span>Send a deletion request to <ContactEmail />.</span></li><li><strong>Identify the account.</strong><span>Include the Instagram business username, business name, and a request to delete account-related data. Do not include passwords or access tokens.</span></li></ol><h2>What happens next</h2><p>We may ask for information needed to verify authority over the business account. After verification, account-related personal and platform data will be deleted or anonymized unless retention is required by law, dispute resolution, fraud prevention, or security obligations.</p><h2>Meta Data Deletion Requests</h2><p>The service supports data deletion requests initiated through Meta&apos;s platform where applicable. If Meta sends a data deletion callback or request, the service will process it according to applicable Meta Platform requirements. This does not represent that a specific callback endpoint is currently available.</p><h2>Contact</h2><p>Deletion requests: <ContactEmail />. Operator: {businessConfig.legalName}, {businessConfig.country}.</p><LegalNotice /></article></section>; }

export function ContactPage() { return <section className="legal-page"><div className="container narrow"><Intro label="Business information" title="Contact"><p>For product, privacy, data deletion, or legal questions, use the details below.</p></Intro><dl className="contact-card"><div><dt>Product</dt><dd>{businessConfig.productName}</dd></div><div><dt>Operator</dt><dd>{businessConfig.legalName}</dd></div><div><dt>Country</dt><dd>{businessConfig.country}</dd></div><div><dt>Email</dt><dd><ContactEmail /></dd></div><div><dt>Website</dt><dd>{businessConfig.websiteUrl}</dd></div></dl><p className="contact-note">No contact form or tracking is used on this website.</p><LegalNotice /></div></section>; }
export function NotFoundPage() { return <section className="legal-page"><div className="container narrow"><Intro label="404" title="Page not found"><p>The page you requested does not exist.</p></Intro></div></section>; }
